import FoodItem from "../../static/images/food-item-1.jpeg";

const foodItemsData = [
	{
		id: 1,
		image: FoodItem,
		hotelName: "Barbeque Delight",
		price: 199,
		dishes: 10,
		rating: "1.7",
		noOfRatings: 213,
		veg: true,
		nonVeg: true,
		discount: "30%",
	},
	{
		id: 2,
		image: FoodItem,
		hotelName: "The FoodBox Club",
		price: 199,
		dishes: 10,
		rating: "4.9",
		noOfRatings: 356,
		veg: false,
		nonVeg: true,
	},
	{
		id: 3,
		image: FoodItem,
		hotelName: "House Warming",
		price: 199,
		dishes: 10,
		rating: "5.0",
		noOfRatings: 450,
		veg: false,
		nonVeg: true,
	},
	{
		id: 4,
		image: FoodItem,
		hotelName: "Meat and Eat",
		price: 199,
		dishes: 10,
		rating: "1.1",
		noOfRatings: 156,
		veg: false,
		nonVeg: true,
	},
	{
		id: 5,
		image: FoodItem,
		hotelName: "Fat Belly",
		price: 199,
		dishes: 10,
		rating: "3.7",
		noOfRatings: 403,
		veg: true,
		nonVeg: false,
	},
	{
		id: 6,
		image: FoodItem,
		hotelName: "The Corner's Cafe",
		price: 199,
		dishes: 10,
		rating: "2.5",
		noOfRatings: 154,
		veg: true,
		nonVeg: true,
	},
	{
		id: 7,
		image: FoodItem,
		hotelName: "The Steaming Mugs",
		price: 199,
		dishes: 10,
		rating: "5.0",
		noOfRatings: 506,
		veg: true,
		nonVeg: false,
	},
	{
		id: 8,
		image: FoodItem,
		hotelName: "Loyans",
		price: 199,
		dishes: 10,
		rating: "3.4",
		noOfRatings: 591,
		veg: true,
		nonVeg: false,
		discount: "40%",
	},
	{
		id: 9,
		image: FoodItem,
		hotelName: "Table Top",
		price: 199,
		dishes: 10,
		rating: "4.7",
		noOfRatings: 496,
		veg: false,
		nonVeg: true,
	},
];

export const getFoodItemsData = () => foodItemsData;
